export type LegacyRouteDefinition = {
  path: string;
  legacyComponent: string;
  area: 'public' | 'auth' | 'couple' | 'vendor' | 'admin';
  clientOnly: boolean;
};

export const legacyRouteDefinitions: LegacyRouteDefinition[] = [
  { path: '/', legacyComponent: '@views/Home', area: 'public', clientOnly: true },
  { path: '/search-vendor', legacyComponent: '@views/SearchVendor', area: 'public', clientOnly: true },
  { path: '/vendor-detail/:vendorId', legacyComponent: '@views/VendorDetail', area: 'public', clientOnly: true },
  { path: '/check-list', legacyComponent: '@views/planning/Checklist', area: 'public', clientOnly: true },
  { path: '/guest-list', legacyComponent: '@views/planning/Guestlist', area: 'public', clientOnly: true },
  { path: '/seating-chart', legacyComponent: '@views/planning/SeatingChart', area: 'public', clientOnly: true },
  { path: '/budget-planner', legacyComponent: '@views/planning/BudgetPlanner', area: 'public', clientOnly: true },
  { path: '/vendors', legacyComponent: '@views/planning/Vendors', area: 'public', clientOnly: true },
  { path: '/dresses', legacyComponent: '@views/planning/Dresses', area: 'public', clientOnly: true },
  { path: '/wedding-website', legacyComponent: '@views/planning/Website', area: 'public', clientOnly: true },
  { path: '/wedding-shoots', legacyComponent: '@views/planning/WedShoots', area: 'public', clientOnly: true },
  { path: '/venues/barn-weddings', legacyComponent: '@views/venue/BarnWeddings', area: 'public', clientOnly: true },
  { path: '/network-error', legacyComponent: '@views/NetworkError', area: 'public', clientOnly: true },
  { path: '/guest-invitation/:coupleData', legacyComponent: '@views/GuestInvitations', area: 'public', clientOnly: true },
  { path: '/login', legacyComponent: '@views/auth/Login', area: 'auth', clientOnly: true },
  { path: '/register', legacyComponent: '@views/auth/Register', area: 'auth', clientOnly: true },
  { path: '/vendor-register', legacyComponent: '@views/auth/VendorRegister', area: 'auth', clientOnly: true },
  { path: '/request-reset-password', legacyComponent: '@views/auth/RequestResetPassword', area: 'auth', clientOnly: true },
  { path: '/reset-password/:hash', legacyComponent: '@views/auth/ResetPassword', area: 'auth', clientOnly: true },
  { path: '/vendor-login', legacyComponent: '@views/auth/VendorLogin', area: 'auth', clientOnly: true },
  { path: '/couple', legacyComponent: '@views/dashboard/couple/pages/MyWedding', area: 'couple', clientOnly: true },
  { path: '/couple/check-list', legacyComponent: '@views/dashboard/couple/pages/Checklist', area: 'couple', clientOnly: true },
  { path: '/couple/vendors', legacyComponent: '@views/dashboard/couple/pages/Vendors', area: 'couple', clientOnly: true },
  { path: '/couple/vendors/search', legacyComponent: '@views/dashboard/couple/pages/VendorsFilters', area: 'couple', clientOnly: true },
  { path: '/couple/guest-list', legacyComponent: '@views/dashboard/couple/pages/GuestList', area: 'couple', clientOnly: true },
  { path: '/couple/seating-chart', legacyComponent: '@views/dashboard/couple/pages/SeatingChart', area: 'couple', clientOnly: true },
  { path: '/couple/budget-planner', legacyComponent: '@views/dashboard/couple/pages/budget-planner/Stats', area: 'couple', clientOnly: true },
  { path: '/couple/budget-planner/:id', legacyComponent: '@views/dashboard/couple/pages/budget-planner/Category', area: 'couple', clientOnly: true },
  { path: '/couple/dresses', legacyComponent: '@views/dashboard/couple/pages/Dresses', area: 'couple', clientOnly: true },
  { path: '/couple/wedding-website', legacyComponent: '@views/dashboard/couple/pages/WeddingWebsite', area: 'couple', clientOnly: true },
  { path: '/couple/web-shoots', legacyComponent: '@views/dashboard/couple/pages/WebShoots', area: 'couple', clientOnly: true },
  { path: '/couple/account', legacyComponent: '@views/dashboard/couple/account/Information', area: 'couple', clientOnly: true },
  { path: '/couple/account/settings', legacyComponent: '@views/dashboard/couple/account/Settings', area: 'couple', clientOnly: true },
  { path: '/couple/account/notifications', legacyComponent: '@views/dashboard/couple/account/Notifications', area: 'couple', clientOnly: true },
  { path: '/venue', legacyComponent: '@views/dashboard/vendor/Dashboard', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront', legacyComponent: 'BusinessDetail', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront/location', legacyComponent: 'BusinessLocation', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront/images', legacyComponent: 'BusinessImages', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront/videos', legacyComponent: 'BusinessVideos', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront/faqs', legacyComponent: 'FAQs', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront/events', legacyComponent: 'BusinessEvents', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront/deals', legacyComponent: 'BusinessDeals', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront/menus', legacyComponent: 'BusinessMenus', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront/social-links', legacyComponent: 'SocialLinks', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront/preferred-vendor', legacyComponent: 'PreferredVendors', area: 'vendor', clientOnly: true },
  { path: '/venue/storefront/tamil-wedding-book-button', legacyComponent: 'TamilWeddingBookButton', area: 'vendor', clientOnly: true },
  { path: '/venue/enquiries', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/venue/enquiries/unread', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/venue/enquiries/read', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/venue/enquiries/pending', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/venue/enquiries/responded', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/venue/enquiries/booked', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/venue/enquiries/export-to-excel', legacyComponent: 'ExportToExcel', area: 'vendor', clientOnly: true },
  { path: '/venue/enquiries/:enquiryId', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/venue/reviews', legacyComponent: 'ReviewCollector', area: 'vendor', clientOnly: true },
  { path: '/venue/reviews/reviews-list', legacyComponent: 'Reviews', area: 'vendor', clientOnly: true },
  { path: '/venue/reviews/badges', legacyComponent: 'Badges', area: 'vendor', clientOnly: true },
  { path: '/venue/reviews/review-widget', legacyComponent: 'ReviewWidget', area: 'vendor', clientOnly: true },
  { path: '/venue/invoices', legacyComponent: 'PaymentsMethods', area: 'vendor', clientOnly: true },
  { path: '/venue/settings', legacyComponent: 'Settings', area: 'vendor', clientOnly: true },
  { path: '/venue/create-storefront', legacyComponent: 'CreateStorefront', area: 'vendor', clientOnly: true },
  { path: '/supplier', legacyComponent: '@views/dashboard/vendor/Dashboard', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront', legacyComponent: 'BusinessDetail', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront/location', legacyComponent: 'BusinessLocation', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront/images', legacyComponent: 'BusinessImages', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront/videos', legacyComponent: 'BusinessVideos', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront/faqs', legacyComponent: 'FAQs', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront/events', legacyComponent: 'BusinessEvents', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront/deals', legacyComponent: 'BusinessDeals', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront/menus', legacyComponent: 'BusinessMenus', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront/social-links', legacyComponent: 'SocialLinks', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront/preferred-vendor', legacyComponent: 'PreferredVendors', area: 'vendor', clientOnly: true },
  { path: '/supplier/storefront/tamil-wedding-book-button', legacyComponent: 'TamilWeddingBookButton', area: 'vendor', clientOnly: true },
  { path: '/supplier/enquiries', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/supplier/enquiries/unread', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/supplier/enquiries/read', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/supplier/enquiries/pending', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/supplier/enquiries/responded', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/supplier/enquiries/booked', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/supplier/enquiries/export-to-excel', legacyComponent: 'ExportToExcel', area: 'vendor', clientOnly: true },
  { path: '/supplier/enquiries/:enquiryId', legacyComponent: 'EnquiriesInbox', area: 'vendor', clientOnly: true },
  { path: '/supplier/reviews', legacyComponent: 'ReviewCollector', area: 'vendor', clientOnly: true },
  { path: '/supplier/reviews/reviews-list', legacyComponent: 'Reviews', area: 'vendor', clientOnly: true },
  { path: '/supplier/reviews/badges', legacyComponent: 'Badges', area: 'vendor', clientOnly: true },
  { path: '/supplier/reviews/review-widget', legacyComponent: 'ReviewWidget', area: 'vendor', clientOnly: true },
  { path: '/supplier/invoices', legacyComponent: 'PaymentsMethods', area: 'vendor', clientOnly: true },
  { path: '/supplier/settings', legacyComponent: 'Settings', area: 'vendor', clientOnly: true },
  { path: '/supplier/create-storefront', legacyComponent: 'CreateStorefront', area: 'vendor', clientOnly: true },

  { path: '/admin', legacyComponent: '@views/dashboard/admin/Dashboard', area: 'admin', clientOnly: true },
  { path: '/admin/login', legacyComponent: 'admin placeholder', area: 'admin', clientOnly: true },
  { path: '/admin/dashboard', legacyComponent: 'admin placeholder', area: 'admin', clientOnly: true },
  { path: '/admin/suppliers', legacyComponent: 'admin placeholder', area: 'admin', clientOnly: true },
  { path: '/admin/venues', legacyComponent: 'admin placeholder', area: 'admin', clientOnly: true },
  { path: '/admin/couples', legacyComponent: 'admin placeholder', area: 'admin', clientOnly: true },
  { path: '/admin/enquiries', legacyComponent: 'admin placeholder', area: 'admin', clientOnly: true },
  { path: '/admin/reviews', legacyComponent: 'admin placeholder', area: 'admin', clientOnly: true },
  { path: '/admin/payments', legacyComponent: 'admin placeholder', area: 'admin', clientOnly: true },
  { path: '/admin/settings', legacyComponent: 'admin placeholder', area: 'admin', clientOnly: true },
];
